blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/kabzon93region/spt-server-editor/discussions
    about: Please ask and answer questions here.
  - name: SPT-AKI Discord
    url: https://discord.gg/sp-tarkov
    about: Join our Discord community for real-time support.
  - name: SPT-AKI Hub
    url: https://hub.sp-tarkov.com/
    about: Visit the SPT-AKI Hub for more information.
